// Side-effect CSS imports (e.g. leaflet/dist/leaflet.css on web). expo-env.d.ts declares this
// too, but it is generated by `expo start` and gitignored — CI and fresh clones don't have it.
declare module '*.css';
